"use client"

import { useState, useEffect } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { useAppStore } from '@/lib/store'
import { getSkipRouteWithParams, FLOW_CONFIG } from '@/lib/flow-config'
import { encodedQuery } from '@/lib/url-cipher'

// G1-Human options
const G1_OPTIONS = [
  { value: 'no', label: 'No, I did not use any AI tools.' },
  { value: 'yes_own_ai', label: 'Yes, I used my own AI (e.g., ChatGPT, Claude...) to help me complete this task.' },
]

// G2-AI options
const G2_OPTIONS = [
  { value: 'no', label: 'No, I did not use AI at all.' },
  { value: 'copy_paste_no_changes', label: 'Yes, I used AI to generate the draft, and then I copied and pasted the text generated by the AI with no changes.' },
  { value: 'copy_paste_edited', label: 'Yes, I used AI to generate the draft, and then I copied and pasted the text generated by the AI, but I edited it in the submission box.' },
]

// G3-HumanAndAI stage1 options
const G3_STAGE1_OPTIONS = [
  { value: 'no', label: 'No' },
  { value: 'yes_own_ai', label: 'Yes, I used my own AI (e.g., ChatGPT, Claude...) to help me complete this task.' },
]

// G3-HumanAndAI stage2 options
const G3_STAGE2_OPTIONS = [
  { value: 'no', label: 'No' },
  { value: 'yes_revise', label: 'Yes, I used AI to revise the draft I wrote in Stage 1.' },
  { value: 'yes_new_answer', label: 'Yes, I used AI to generate a new answer rather than to revise the draft I wrote.' },
]

export default function ManipulationCheckPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const taskId = useAppStore((s) => s.taskId)
  const userId = useAppStore((s) => s.userId)
  const prolificId = useAppStore((s) => s.prolificId)
  const groupType = useAppStore((s) => s.groupType)
  const setManipulationCheckCompleted = useAppStore((s) => s.setManipulationCheckCompleted)

  const [g1Answer, setG1Answer] = useState<string | undefined>(undefined)
  const [g2Answer, setG2Answer] = useState<string | undefined>(undefined)
  const [g3Stage1Answer, setG3Stage1Answer] = useState<string | undefined>(undefined)
  const [g3Stage2Answer, setG3Stage2Answer] = useState<string | undefined>(undefined)

  const [error, setError] = useState<string>('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [showConfirmDialog, setShowConfirmDialog] = useState(false)
  const [showBackDialog, setShowBackDialog] = useState(false)

  // Block browser back navigation
  useEffect(() => {
    const preventBack = (e: PopStateEvent) => {
      e.preventDefault()
      window.history.pushState(null, '', window.location.href)
      setShowBackDialog(true)
    }
    window.history.pushState(null, '', window.location.href)
    window.addEventListener('popstate', preventBack)
    return () => {
      window.removeEventListener('popstate', preventBack)
    }
  }, [])

  // Skip when disabled
  useEffect(() => {
    if (!FLOW_CONFIG.manipulationCheck) {
      const skip = getSkipRouteWithParams('manipulationCheck', searchParams)
      if (skip) router.replace(skip)
      else router.replace('/thank-you')
    }
  }, [router, searchParams, setManipulationCheckCompleted])

  const allRequiredAnswered = (): boolean => {
    if (!groupType) return false
    if (groupType === 'G1-Human') return g1Answer !== undefined
    if (groupType === 'G2-AI') return g2Answer !== undefined
    if (groupType === 'G3-HumanAndAI') return g3Stage1Answer !== undefined && g3Stage2Answer !== undefined
    return false
  }

  const handleNext = () => {
    if (!allRequiredAnswered()) {
      setError('Please answer all required questions before proceeding.')
      return
    }
    setError('')
    setShowConfirmDialog(true)
  }

  const handleConfirmSubmit = async () => {
    setShowConfirmDialog(false)
    setIsSubmitting(true)

    const eq = encodedQuery(searchParams)
    const qs = eq ? eq : ''

    try {
      const body: Record<string, unknown> = {
        userId,
        prolificId,
        groupType,
        taskId,
      }

      if (groupType === 'G1-Human') {
        body.aiUsedStage1 = g1Answer
      } else if (groupType === 'G2-AI') {
        body.aiUsedStage1 = g2Answer
      } else if (groupType === 'G3-HumanAndAI') {
        body.aiUsedStage1 = g3Stage1Answer
        body.aiUsedStage2 = g3Stage2Answer
      }

      const response = await fetch('/api/manipulation-check', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })

      if (response.ok) {
        setManipulationCheckCompleted(true)
        router.replace(`/thank-you${qs}`)
      } else {
        setError('Failed to save your responses. Please try again.')
        setIsSubmitting(false)
      }
    } catch {
      setError('Network error. Please try again.')
      setIsSubmitting(false)
    }
  }

  const renderRadioGroup = (
    name: string,
    value: string | undefined,
    options: { value: string; label: string }[],
    onChange: (v: string) => void
  ) => (
    <RadioGroup value={value || ''} onValueChange={onChange}>
      <div className="flex flex-col gap-2">
        {options.map((opt) => (
          <div key={opt.value} className="flex items-start gap-2">
            <RadioGroupItem value={opt.value} id={`${name}-${opt.value}`} className="mt-1" />
            <Label htmlFor={`${name}-${opt.value}`} className="cursor-pointer text-sm leading-tight">
              {opt.label}
            </Label>
          </div>
        ))}
      </div>
    </RadioGroup>
  )

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-gray-100 py-8 px-4">
      <Card className="max-w-3xl w-full mx-auto">
        <CardHeader>
          <CardTitle className="text-2xl font-bold text-center">
            Supplemental Question
          </CardTitle>
          <p className="text-center text-gray-500 text-sm mt-1">
            Please answer the following question about how you completed the task.
          </p>
        </CardHeader>

        <CardContent className="space-y-6 pb-2">
          {groupType === 'G1-Human' && (
            <div className="space-y-3">
              <Label className="text-base font-medium">
                Did you use any AI tools (e.g., ChatGPT) in the task you just completed? Your compensation will not be affected by your answer. Your honest answer is very important to our study. Thank you! <span className="text-red-500">*</span>
              </Label>
              {renderRadioGroup('g1-ai-used', g1Answer, G1_OPTIONS, setG1Answer)}
            </div>
          )}

          {groupType === 'G2-AI' && (
            <div className="space-y-3">
              <Label className="text-base font-medium">
                Did you use any AI tools (e.g., ChatGPT) in the task you just completed? Your compensation will not be affected by your answer. Your honest answer is very important to our study. Thank you! <span className="text-red-500">*</span>
              </Label>
              {renderRadioGroup('g2-ai-used', g2Answer, G2_OPTIONS, setG2Answer)}
            </div>
          )}

          {groupType === 'G3-HumanAndAI' && (
            <>
              <div className="space-y-3">
                <Label className="text-base font-medium">
                  Did you use any AI tools (e.g., ChatGPT) in the task you just completed? Your compensation will not be affected by your answer. Your honest answer is very important to our study. Thank you! <span className="text-red-500">*</span>
                </Label>
                <div className="bg-gray-50 p-4 rounded-lg border space-y-4">
                  <div className="space-y-2">
                    <p className="text-sm font-medium text-gray-700">In the first stage (writing the draft):</p>
                    {renderRadioGroup('g3-stage1', g3Stage1Answer, G3_STAGE1_OPTIONS, setG3Stage1Answer)}
                  </div>
                  <div className="border-t pt-3 space-y-2">
                    <p className="text-sm font-medium text-gray-700">In the second stage (revising):</p>
                    {renderRadioGroup('g3-stage2', g3Stage2Answer, G3_STAGE2_OPTIONS, setG3Stage2Answer)}
                  </div>
                </div>
              </div>
            </>
          )}

          {error && (
            <p className="text-sm text-red-500 text-center">{error}</p>
          )}
        </CardContent>

        <div className="px-6 pb-6">
          <Button
            onClick={handleNext}
            disabled={isSubmitting}
            size="lg"
            className="w-full"
          >
            {isSubmitting ? 'Submitting...' : 'Submit'}
          </Button>
        </div>
      </Card>

      {/* Confirm Dialog */}
      <Dialog open={showConfirmDialog} onOpenChange={setShowConfirmDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Submit?</DialogTitle>
            <DialogDescription>
              Are you sure you want to submit your answers? This will complete the study.
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-end gap-3 pt-4">
            <Button variant="outline" onClick={() => setShowConfirmDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handleConfirmSubmit} disabled={isSubmitting}>
              {isSubmitting ? 'Submitting...' : 'Yes, Submit'}
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Back Navigation Warning Dialog */}
      <Dialog open={showBackDialog} onOpenChange={setShowBackDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Warning: Page Navigation Blocked</DialogTitle>
            <DialogDescription>
              You cannot go back to the previous step. Once you leave this page, your responses cannot be changed.
              <br /><br />
              If you accidentally navigate away, you will need to start the entire study over.
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-end pt-4">
            <Button onClick={() => setShowBackDialog(false)}>
              Stay on This Page
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}
